export const projects = [
  {
    title: 'HotStar Clone',
    description: "A Disney+ HotStar Clone static website using HTML, CSS & JavaScript.",
    image: '/images/3.png',
    tags: ['HTML, CSS, JavaScript'],
    source: 'https://github.com/KingDez04/HotStar_Clone',
    visit: 'https://ademolaademeso-hot-star-clone.vercel.app/',
    id: 0,
  },
  {
    title: 'Calculator',
    description: "A simple calculator app using HTML, CSS & JavaScript.",
    image: '/images/8.jpg',
    tags: ['HTML, CSS, JavaScript'],
    source: 'https://github.com/KingDez04/Calc',
    visit: 'https://ademolaademeso-calculator.vercel.app/',
    id: 1,
  },
  {
    title: 'TicTacToe',
    description: "A python application that accepts user input and simulates both multiplayer and single player mode using min max algorithm.",
    image: '/images/1.png',
    tags: ['Python'],
    source: 'https://github.com/KingDez04/Py/blob/main/tictactoe.py',
    visit: 'https://github.com/KingDez04/Py/blob/main/tictactoe.py',
    id: 2,
  },
  {
    title: 'Rcrsv Fact',
    description: "The program is called RcrsvFact and it is a simple C++ program that allows users to generate the factorial of an integer through recursion.",
    image: '/images/5.webp',
    tags: ['C++'],
    source: 'https://github.com/KingDez04/RcrsvFact/tree/master/RcrsvFnctn(fact)',
    visit: 'https://github.com/KingDez04/RcrsvFact/tree/master/RcrsvFnctn(fact)',
    id: 3,
  },
  {
    title: 'ATM',
    description:"Console application that allows a user to simulate the workings of an ATM machine.",
    image: '/images/2.JPG',
    tags: ['C++'],
    source: 'https://github.com/KingDez04/RcrsvFact/tree/master/ATM',
    visit: 'https://github.com/KingDez04/RcrsvFact/tree/master/ATM',
    id: 4,
  },
  {
    title: 'Pswrd',
    description: "Password Verification console application.",
    image: '/images/7.jpg',
    tags: ['C++'],
    source: 'https://github.com/KingDez04/RcrsvFact/tree/master/Pswrd',
    visit: 'https://github.com/KingDez04/RcrsvFact/tree/master/Pswrd',
    id: 5,
  },
];

export const TimeLineData = [
  { year: 2021, text: 'Graphics Designer at True Arts Academy', },
  { year: 2022, text: 'Got my first Tech-certificate on the theoretical understanding of HTML', },
  { year: 2022, text: 'Started studying Computer Science at Babcock University', },
  { year: 2023, text: 'Accepted into the Software Engineering Programme at ALX', },
];
